name: Build and Publish Tailscale Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version info environment variables
        run: |
          echo "VERSION_LONG=$(git describe --long --always)" >> $GITHUB_ENV
          echo "VERSION_SHORT=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          echo "VERSION_GIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Run build script
        run: |
          chmod +x ./build.sh
          ./build.sh
